### ISSUE TITLE
stale constraint

### ISSUE THREAD

**Issue by dabrahams** [val-lang/val#639]
I got this, which looks like an internal error: “stale constraint 'Int ⤷ %350'” by running this (incorrect) val code with the tip of my test-generation branch:

```
//- compileAndRun expecting: success

fun factorial(_ n: Int) -> Int {
  if n < 2 { 1 } else { n * factorial(n - 1) }
}

fun assert(_ b: Bool) {
  if !b + 2 {
    let _ = fatal_error()
  }
}

public fun main() {
  let r = factorial(6)
  assert(r == 720)
}
```

**Comment by dabrahams** [comment]
(I get the same result after merging main into my branch)

**Comment by kyouko-taiga** [comment]
FYI, "stale" constraints occur when the solver is given an underspecified constraint system and doesn't know how to diagnose the situation. They should only occur when we're trying to type check illegal Val code.

One way to investigate what happens is to pass `--trace-inference path/to/source.val:123` (where 123 is the line at which the expression occurs). For your test case, here's what we get:

```
Inferring type of '!b + 2' at test.val:8:6
---
fresh:
- "%138.infix+ == [{self: remote let %138}] (%139) let -> %140"
- "Int ⤷ %139"
- "([{self: remote let Bool}] () let -> Bool)() -> %138"
- "%137 <: Bool"
- "%140 == %137"
stale:
steps:
- solve: "%140 == %137"
  actions:
  - assume: "%140 = %137"
  - success
- solve: "%137 <: Bool"
  actions:
  - assume: "%137 = Bool"
  - success
- solve: "([{self: remote let Bool}] () let -> Bool)() -> %138"
  actions:
  - schedule: "Bool == %138"
  - break
- solve: "Bool == %138"
  actions:
  - assume: "%138 = Bool"
  - success
- solve: "Int ⤷ %139"
  actions:
  - defer
- solve: "Bool.infix+ == [{self: remote let %138}] (%139) let -> %140"
  actions:
  - failure
- failure
```

That should be enough to help me fix the issue.
